project_id = "zhrdffknxyixjgivlwii"

[functions.shopify-webhook]
verify_jwt = false

[functions.import-shopify-orders]
verify_jwt = false

[functions.import-bestbuy-orders]
verify_jwt = false

[functions.import-amazon-orders]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.process-sale-accounting]
verify_jwt = false

[functions.ai-forecast]
verify_jwt = false

[functions.process-return-accounting]
verify_jwt = false

[functions.process-intercompany-accounting]
verify_jwt = false

[functions.run-data-validation]
verify_jwt = false
